"""rename address

Revision ID: 1acf942abff3
Revises: eca4353604ff
Create Date: 2024-04-03 14:39:17.498208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1acf942abff3'
down_revision = 'eca4353604ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments','address',new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments','location', new_column_name='address')
    # ### end Alembic commands ###
